language: node_js
node_js: 
  - 12
before_install: 
  - npm install -g vuepress
install:
  - npm install
script:
  - vuepress build docs
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  traget-branch: gh-pages
  local-dir: ./docs/.vuepress/dist
  verbose: true
  on:
    branch: master
after_success:
  - echo success